-- Make sure briefs table exists
CREATE TABLE IF NOT EXISTS briefs (
  id VARCHAR(36) PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Add EVERY column the app expects (safe: does nothing if already present)
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS business_name TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS business_type TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS old_website TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS business_description TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS project_type TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS budget TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS timeline TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS language TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS questionnaire JSONB;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS audio_url TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS user_agent TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS ip_address TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS referrer TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS landing_page TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS time_on_site INTEGER;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS device_type TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS browser_name TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS os_name TEXT;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS screen_width INTEGER;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS screen_height INTEGER;