import { pgTable, text, timestamp, varchar, boolean, json, integer } from 'drizzle-orm/pg-core';

export const briefs = pgTable('briefs', {
  id: varchar('id', { length: 36 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
  name: text('name').notNull(),
  email: text('email').notNull(),
  phone: text('phone'),
  businessName: text('business_name'),
  businessType: text('business_type'),
  businessDescription: text('business_description'),
  projectType: text('project_type'),
  budget: text('budget'),
  timeline: text('timeline'),
  language: text('language'),
  questionnaire: json('questionnaire'),
  userAgent: text('user_agent'),
  ipAddress: text('ip_address'),
  country: text('country'),
  city: text('city'),
  referrer: text('referrer'),
  landingPage: text('landing_page'),
  timeOnSite: integer('time_on_site'),
  deviceType: text('device_type'),
  browserName: text('browser_name'),
  osName: text('os_name'),
  screenWidth: integer('screen_width'),
  screenHeight: integer('screen_height'),
  audioUrl: text('audio_url'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

export const visitors = pgTable('visitors', {
  id: varchar('id', { length: 36 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
  sessionId: text('session_id'),
  userAgent: text('user_agent'),
  ipAddress: text('ip_address'),
  country: text('country'),
  city: text('city'),
  referrer: text('referrer'),
  landingPage: text('landing_page'),
  currentPage: text('current_page'),
  timeOnPage: integer('time_on_page'),
  timeOnSite: integer('time_on_site'),
  deviceType: text('device_type'),
  browserName: text('browser_name'),
  browserVersion: text('browser_version'),
  osName: text('os_name'),
  osVersion: text('os_version'),
  screenWidth: integer('screen_width'),
  screenHeight: integer('screen_height'),
  screenColorDepth: integer('screen_color_depth'),
  language: text('language'),
  timezone: text('timezone'),
  isFirstVisit: boolean('is_first_visit').default(false),
  visitCount: integer('visit_count').default(1),
  metadata: json('metadata'),
  audioUrl: text('audio_url'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

export const pageViews = pgTable('page_views', {
  id: varchar('id', { length: 36 }).primaryKey().$defaultFn(() => crypto.randomUUID()),
  sessionId: text('session_id').notNull(),
  visitorId: varchar('visitor_id', { length: 36 }).references(() => visitors.id),
  page: text('page').notNull(),
  referrer: text('referrer'),
  timeOnPage: integer('time_on_page'),
  scrollDepth: integer('scroll_depth'),
  audioUrl: text('audio_url'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});